<?php
/**
 * Copyright (c) 2024 Attila Sagi
 * @license http://www.opensource.org/licenses/mit-license.html  MIT License
 */

/**
 * @var $block \Space\Blog\Block\View\Post
 * @var $escaper \Magento\Framework\Escaper;
 * @var $viewModel \Space\Blog\ViewModel\View\PostRenderer
 */
?>
<?php $viewModel = $block->getData('view_model'); ?>
<?php $post = $viewModel->getPost(); ?>
<?php if (null !== $post && $post->getId()): ?>
    <div class="space-blog">
        <h2><?= $escaper->escapeHtml($post->getTitle()) ?></h2>
        <?= $escaper->escapeHtml(
            __('Date: %1', $block->formatDate($post->getUpdateTime(), \IntlDateFormatter::SHORT, true))
        ) ?>,
        <span><?= $escaper->escapeHtml(__('by: %1', $post->getAuthor())) ?></span>
        <p style="margin-top: 10px">
            <?= $escaper->escapeHtml($post->getContent()); ?>
        </p>
        <a href="<?= $escaper->escapeUrl($viewModel->getBackUrl()) ?>"
           title="<?= $escaper->escapeHtml(__('Back')) ?>">
            <span><?= $escaper->escapeHtml(__('Back')) ?></span>
        </a>
    </div>
<?php else: ?>
    <p class="error"><?= $escaper->escapeHtml(__('Post not found.')) ?></p>
<?php endif; ?>
